"use client";
import { useState } from "react";
import { getSupabaseBrowser } from "@/lib/supabaseBrowser";
import { V } from "@/lib/theme";

type Item={id:string;kind:"quote"|"change-order";title:string;status:string;amountCents:number;version?:number;scope?:string|null;notes?:string|null;sentAt?:string|null;respondedAt?:string|null};
export default function ClientCommercialApprovals({initial,onChanged}:{initial:Item[];onChanged?:()=>void}){
  const[items,setItems]=useState(initial),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
  async function decide(item:Item,decision:string){setBusy(item.id);setError(null);const sb=getSupabaseBrowser();const{data}=await sb.auth.getSession();const response=await fetch(`/api/client/commercial/${item.kind}/${item.id}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token??""}`},body:JSON.stringify({decision,notes:notes[item.id]??""})});const body=await response.json().catch(()=>({}));if(!response.ok)setError(body.error??"Decision could not be saved");else{setItems(current=>current.map(entry=>entry.id===item.id?{...entry,status:decision,respondedAt:new Date().toISOString()}:entry));onChanged?.()}setBusy(null)}
  if(!items.length)return <p style={muted}>No commercial approvals are waiting.</p>;
  return <div style={{display:"grid",gap:10}}>{error&&<p role="alert" style={{color:V.danger,fontSize:12}}>{error}</p>}{items.map(item=><div key={item.kind+item.id} style={{padding:12,border:`1px solid ${item.status==="sent"?V.signal:V.line}`,borderRadius:10,background:V.raised}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><strong>{item.title}</strong><div style={muted}>{item.kind==="quote"?`Quote version ${item.version??1}`:"Change order"} · {(item.amountCents/100).toLocaleString("en-US",{style:"currency",currency:"USD"})}</div></div><span style={{fontSize:11,textTransform:"uppercase",color:item.status==="accepted"||item.status==="approved"?V.telemetry:item.status==="rejected"?V.danger:item.status==="sent"?V.signal:V.inkDim}}>{item.status}</span></div>{item.scope&&<p style={{...muted,whiteSpace:"pre-wrap",marginTop:8}}>{item.scope}</p>}{item.status==="sent"&&<><textarea value={notes[item.id]??""} onChange={event=>setNotes(current=>({...current,[item.id]:event.target.value}))} placeholder="Optional note with your decision" style={{width:"100%",minHeight:64,marginTop:9,padding:9,borderRadius:8,border:`1px solid ${V.line}`,background:V.surface,color:V.ink}}/><div style={{display:"flex",gap:8,marginTop:8}}><button disabled={busy===item.id} onClick={()=>decide(item,item.kind==="quote"?"accepted":"approved")} style={primary}>Accept</button><button disabled={busy===item.id} onClick={()=>decide(item,"rejected")} style={reject}>Reject</button></div></>}</div>)}</div>
}
const muted:React.CSSProperties={color:V.inkDim,fontSize:12};const primary:React.CSSProperties={padding:"7px 12px",border:0,borderRadius:7,background:V.telemetry,color:V.ground,fontWeight:700,cursor:"pointer"};const reject:React.CSSProperties={...primary,background:"transparent",color:V.danger,border:`1px solid ${V.danger}`};
