"use client";
import { useCallback, useEffect, useState } from "react";
import { getSupabaseBrowser } from "@/lib/supabaseBrowser";
import { V } from "@/lib/theme";

type Target = { type: "pilot"|"dom"|"client"|"mission"; label: string; description: string };
type Review = { target_type:string; overall_rating:number; communication_rating:number|null; preparedness_rating:number|null; accuracy_rating:number|null; would_work_again:boolean|null; comments:string|null; private_notes:string|null };

export default function MissionReviewPanel({ endpoint, targets, enabled=true }: { endpoint:string; targets:Target[]; enabled?:boolean }) {
  const [reviews,setReviews]=useState<Record<string,Review>>({}); const [active,setActive]=useState(targets[0]?.type??"mission"); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const load=useCallback(async()=>{const {data}=await getSupabaseBrowser().auth.getSession();if(!data.session)return;const r=await fetch(endpoint,{headers:{Authorization:`Bearer ${data.session.access_token}`}});if(r.ok){const body=await r.json();setReviews(Object.fromEntries((body.reviews??[]).map((x:Review)=>[x.target_type,x])))}},[endpoint]);
  useEffect(()=>{load()},[load]); const existing=reviews[active]; const [overall,setOverall]=useState(5); const [communication,setCommunication]=useState(5); const [preparedness,setPreparedness]=useState(5); const [accuracy,setAccuracy]=useState(5); const [again,setAgain]=useState(true); const [comments,setComments]=useState(""); const [privateNotes,setPrivateNotes]=useState("");
  useEffect(()=>{const r=reviews[active];setOverall(r?.overall_rating??5);setCommunication(r?.communication_rating??5);setPreparedness(r?.preparedness_rating??5);setAccuracy(r?.accuracy_rating??5);setAgain(r?.would_work_again??true);setComments(r?.comments??"");setPrivateNotes(r?.private_notes??"")},[active,reviews]);
  async function save(){setSaving(true);setMessage(null);const {data}=await getSupabaseBrowser().auth.getSession();const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token??""}`},body:JSON.stringify({targetType:active,overallRating:overall,communicationRating:communication,preparednessRating:preparedness,accuracyRating:accuracy,wouldWorkAgain:again,comments,privateNotes})});const out=await r.json();setMessage(r.ok?"Review saved.":out.error??"Could not save review.");setSaving(false);if(r.ok)load()}
  if(!targets.length)return null; return <section style={{marginTop:16,padding:16,border:`1px solid ${V.line}`,borderRadius:12,background:V.raised}}><h3 style={{fontSize:13,fontWeight:700}}>Mission reviews</h3><p style={{color:V.inkDim,fontSize:12,marginTop:4}}>Rate the people and experience separately. Internal notes are visible only to DOM operations.</p><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:12}}>{targets.map(t=><button key={t.type} onClick={()=>setActive(t.type)} style={{...chip,background:active===t.type?V.signal:"transparent",color:active===t.type?V.ground:V.ink}}>{t.label}{reviews[t.type]?" ✓":""}</button>)}</div><p style={{color:V.inkDim,fontSize:11,marginTop:8}}>{targets.find(t=>t.type===active)?.description}</p>{enabled?<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:9,marginTop:12}}><Stars label="Overall" value={overall} set={setOverall}/><Stars label="Communication" value={communication} set={setCommunication}/><Stars label="Preparedness" value={preparedness} set={setPreparedness}/><Stars label="Scope accuracy" value={accuracy} set={setAccuracy}/></div><label style={{display:"flex",gap:8,alignItems:"center",fontSize:12,marginTop:12}}><input type="checkbox" checked={again} onChange={e=>setAgain(e.target.checked)}/> I would work with this person/company again</label><textarea value={comments} onChange={e=>setComments(e.target.value)} placeholder="Share useful, professional feedback…" style={textarea}/><textarea value={privateNotes} onChange={e=>setPrivateNotes(e.target.value)} placeholder="Private DOM operations notes (never shown publicly)…" style={textarea}/><button onClick={save} disabled={saving} style={primary}>{saving?"Saving…":existing?"Update review":"Submit review"}</button>{message&&<span style={{color:message.includes("saved")?V.telemetry:V.danger,fontSize:12,marginLeft:9}}>{message}</span>}</>:<p style={{color:V.warn,fontSize:12,marginTop:12}}>Reviews unlock when the mission is delivered or completed.</p>}</section>;
}
function Stars({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <div><div style={{color:V.inkFaint,fontSize:10,textTransform:"uppercase"}}>{label}</div><div aria-label={`${label}: ${value} stars`}>{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>set(n)} style={{border:0,background:"transparent",color:n<=value?V.warn:V.inkFaint,fontSize:22,padding:"2px",cursor:"pointer"}}>★</button>)}</div></div>}
const chip:React.CSSProperties={padding:"6px 10px",borderRadius:20,border:`1px solid ${V.line}`,fontSize:11,cursor:"pointer"}; const textarea:React.CSSProperties={width:"100%",minHeight:65,marginTop:10,padding:9,borderRadius:8,border:`1px solid ${V.line}`,background:V.surface,color:V.ink}; const primary:React.CSSProperties={marginTop:10,padding:"8px 13px",borderRadius:8,border:0,background:V.signal,color:V.ground,fontWeight:700,cursor:"pointer"};
