"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabaseBrowser } from "@/lib/supabaseBrowser";
import { V } from "@/lib/theme";

const CADENCES = ["weekly", "biweekly", "monthly", "quarterly", "semiannual", "annual", "custom"];
const empty = { name: "", client_id: "", service_type: "construction_progress", location: "", scope: "", cadence: "monthly", cadence_days: "", next_due_on: new Date().toISOString().slice(0, 10), default_quote: "" };

export default function ProgramsPage() {
  const router = useRouter();
  const [programs, setPrograms] = useState<any[]>([]); const [clients, setClients] = useState<any[]>([]); const [missions, setMissions] = useState<any[]>([]); const [costs, setCosts] = useState<any[]>([]); const [draft, setDraft] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const sb = getSupabaseBrowser(); const { data: session } = await sb.auth.getSession(); if (!session.session) { router.push("/admin/login"); return; } const [p, c, m, co] = await Promise.all([sb.from("mission_programs").select("*, client:clients(company_name)").order("next_due_on"), sb.from("clients").select("id, company_name").order("company_name"), sb.from("mission_requests").select("id,status,quoted_amount_cents,created_at,jobs(id,completed_at,actual_duration_minutes,assignments(id,status))"), sb.from("mission_cost_entries").select("actual_cents,estimated_cents")]); if (p.error && p.error.code !== "42P01") setError(p.error.message); setPrograms(p.data ?? []); setClients(c.data ?? []); setMissions(m.data ?? []); setCosts(co.data ?? []); setLoading(false); }, [router]);
  useEffect(() => { load(); }, [load]);
  const analytics = useMemo(() => { const completed = missions.filter((m) => ["delivered", "closed"].includes(m.status)); const revenue = missions.reduce((sum, m) => sum + (m.quoted_amount_cents ?? 0), 0); const cost = costs.reduce((sum, c) => sum + (c.actual_cents ?? c.estimated_cents ?? 0), 0); const cycle = completed.map((m) => { const done = m.jobs?.[0]?.completed_at; return done ? (new Date(done).getTime() - new Date(m.created_at).getTime()) / 86400000 : null; }).filter((v): v is number => v != null); const assigned = missions.filter((m) => m.jobs?.[0]?.assignments?.length).length; return { total: missions.length, completed: completed.length, revenue, margin: revenue ? ((revenue - cost) / revenue) * 100 : 0, cycle: cycle.length ? cycle.reduce((a, b) => a + b, 0) / cycle.length : 0, assignmentRate: missions.length ? assigned / missions.length * 100 : 0 }; }, [missions, costs]);

  async function createProgram() { setSaving(true); setError(null); const sb = getSupabaseBrowser(); const { error: insertError } = await sb.from("mission_programs").insert({ name: draft.name.trim(), client_id: draft.client_id || null, service_type: draft.service_type, location: draft.location.trim(), scope: draft.scope.trim() || null, cadence: draft.cadence, cadence_days: draft.cadence === "custom" ? Number(draft.cadence_days) || null : null, next_due_on: draft.next_due_on, default_quote_cents: draft.default_quote ? Math.round(Number(draft.default_quote) * 100) : null }); if (insertError) setError(insertError.message); else { setDraft(empty); await load(); } setSaving(false); }
  async function setStatus(id: string, status: string) { const sb = getSupabaseBrowser(); await sb.from("mission_programs").update({ status, updated_at: new Date().toISOString() }).eq("id", id); await load(); }

  return <main className="section"><div className="container-app"><p className="eyebrow mb-2">Portfolio Operations</p><h1 className="heading-lg">Programs & Analytics</h1><p className="body-muted mt-2">Manage repeatable client work and see the operating health of DOM at a glance.</p>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: 10, marginTop: 22 }}><Stat label="Missions" value={analytics.total.toString()} /><Stat label="Completed" value={analytics.completed.toString()} /><Stat label="Booked revenue" value={money(analytics.revenue)} /><Stat label="Gross margin" value={`${analytics.margin.toFixed(1)}%`} /><Stat label="Avg. cycle" value={`${analytics.cycle.toFixed(1)} days`} /><Stat label="Assignment rate" value={`${analytics.assignmentRate.toFixed(0)}%`} /></div>
    {error && <p style={{ color: V.danger, marginTop: 14 }}>{error}</p>}
    <div style={{ display: "grid", gridTemplateColumns: "minmax(300px,.8fr) minmax(420px,1.2fr)", gap: 18, marginTop: 20 }}><section className="card p-6"><h2 className="font-saira" style={{ fontSize: 18 }}>Create recurring program</h2><div style={{ display: "grid", gap: 10, marginTop: 14 }}><input style={input} placeholder="Program name" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /><select style={input} value={draft.client_id} onChange={e => setDraft({ ...draft, client_id: e.target.value })}><option value="">No client linked</option>{clients.map(c => <option key={c.id} value={c.id}>{c.company_name}</option>)}</select><input style={input} placeholder="Mission location" value={draft.location} onChange={e => setDraft({ ...draft, location: e.target.value })} /><input style={input} placeholder="Service type" value={draft.service_type} onChange={e => setDraft({ ...draft, service_type: e.target.value })} /><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}><select style={input} value={draft.cadence} onChange={e => setDraft({ ...draft, cadence: e.target.value })}>{CADENCES.map(c => <option key={c}>{c}</option>)}</select><input style={input} type="date" value={draft.next_due_on} onChange={e => setDraft({ ...draft, next_due_on: e.target.value })} /></div>{draft.cadence === "custom" && <input style={input} type="number" placeholder="Repeat every N days" value={draft.cadence_days} onChange={e => setDraft({ ...draft, cadence_days: e.target.value })} />}<input style={input} type="number" placeholder="Default quote ($)" value={draft.default_quote} onChange={e => setDraft({ ...draft, default_quote: e.target.value })} /><textarea style={{ ...input, minHeight: 84, resize: "vertical" }} placeholder="Standard scope and deliverables" value={draft.scope} onChange={e => setDraft({ ...draft, scope: e.target.value })} /><button style={button} disabled={saving || !draft.name.trim() || !draft.location.trim()} onClick={createProgram}>{saving ? "Creating…" : "Create Program"}</button></div></section>
      <section className="card p-6"><div style={{ display: "flex", justifyContent: "space-between" }}><h2 className="font-saira" style={{ fontSize: 18 }}>Recurring mission programs</h2><span style={{ color: V.inkDim, fontSize: 12 }}>{programs.filter(p => p.status === "active").length} active</span></div><div style={{ display: "grid", gap: 10, marginTop: 14 }}>{loading && <p className="body-muted">Loading programs…</p>}{!loading && !programs.length && <p className="body-muted">No recurring programs yet.</p>}{programs.map(p => <div key={p.id} style={{ padding: 13, border: `1px solid ${V.line}`, borderLeft: `5px solid ${p.status === "active" ? V.telemetry : V.warn}`, borderRadius: 10, background: V.raised }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><div><strong>{p.name}</strong><div style={{ color: V.inkDim, fontSize: 12 }}>{p.client?.company_name ?? "Unlinked client"} · {p.location}</div></div><span style={{ textTransform: "uppercase", fontSize: 10, color: p.status === "active" ? V.telemetry : V.warn }}>{p.status}</span></div><div style={{ display: "flex", justifyContent: "space-between", gap: 10, marginTop: 9, alignItems: "center" }}><span style={{ color: V.inkFaint, fontSize: 11 }}>{p.cadence} · next due {new Date(`${p.next_due_on}T12:00:00`).toLocaleDateString()}</span><button style={mini} onClick={() => setStatus(p.id, p.status === "active" ? "paused" : "active")}>{p.status === "active" ? "Pause" : "Activate"}</button></div></div>)}</div></section></div>
  </div></main>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="card p-4"><div style={{ color: V.inkFaint, fontSize: 10, textTransform: "uppercase" }}>{label}</div><div className="font-saira" style={{ fontSize: 22, fontWeight: 800, marginTop: 3 }}>{value}</div></div>; }
const money = (cents: number) => (cents / 100).toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const input: React.CSSProperties = { width: "100%", padding: "9px 10px", borderRadius: 8, border: `1px solid ${V.line}`, background: V.raised, color: V.ink };
const button: React.CSSProperties = { ...input, background: V.signal, color: V.ground, fontWeight: 800, cursor: "pointer" };
const mini: React.CSSProperties = { padding: "5px 9px", borderRadius: 6, border: `1px solid ${V.line}`, background: V.surface, color: V.ink, fontSize: 11, cursor: "pointer" };
