export const WORKFLOW_ITEMS = [
  ["planning","scope_reviewed","Review client scope and deliverables"],
  ["planning","uav_assigned","Assign the mission UAV"],
  ["planning","insurance_verified","Mandatory insurance verification"],
  ["planning","schedule_confirmed","Confirm performance date and backup window"],
  ["planning","airspace_reviewed","Review airspace, TFRs, NOTAMs, and authorization"],
  ["planning","weather_reviewed","Review forecast, winds, gusts, visibility, and precipitation"],
  ["planning","site_access_confirmed","Confirm site access, parking, check-in, and contacts"],
  ["preflight","credentials_current","Confirm Part 107, insurance, and Remote ID readiness"],
  ["preflight","site_safety_ppe","Confirm site PPE, high-visibility vest, cones, DOM barrier poles, signage, and perimeter controls"],
  ["preflight","aircraft_inspected","Inspect aircraft, props, payload, storage, firmware, and controller"],
  ["preflight","batteries_ready","Confirm charged flight/controller batteries and reserves"],
  ["preflight","rth_lost_link","Set RTH altitude and lost-link behavior for the site"],
  ["onsite","site_walk","Complete site walk and identify people, obstacles, wires, animals, and hazards"],
  ["onsite","weather_recheck","Recheck current weather and go/no-go decision"],
  ["onsite","authorization_active","Confirm authorization is active for the operating window"],
  ["flight","capture_complete","Complete the required capture plan"],
  ["flight","coverage_verified","Review coverage and image quality before leaving"],
  ["postflight","aircraft_postflight","Complete postflight aircraft and battery inspection"],
  ["postflight","media_backed_up","Back up and verify all mission media"],
  ["submission","deliverables_uploaded","Upload required files and field notes"],
  ["submission","mission_submitted","Submit mission to DOM for QC"],
] as const;
