"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import BarrierProductVisual from "@/components/shop/BarrierProductVisual";
import { getSupabaseBrowser } from "@/lib/supabaseBrowser";

type Product = { product_key: string; product_name: string; description: string; unit_amount_cents: number; variants: string[]; category: string; image_url: string | null; fulfillment_mode: string; available_quantity: number | null; shipping_base_cents: number; shipping_additional_cents: number; active: boolean };
type Draft = { productKey: string; productName: string; description: string; price: string; variants: string; category: string; imageUrl: string; fulfillmentMode: string; availableQuantity: string; shippingBase: string; shippingAdditional: string; active: boolean };
const emptyDraft: Draft = { productKey: "", productName: "", description: "", price: "0.00", variants: "", category: "Equipment", imageUrl: "", fulfillmentMode: "made_to_order", availableQuantity: "0", shippingBase: "0.00", shippingAdditional: "0.00", active: true };

export default function AdminProductsPage() {
  const editorRef = useRef<HTMLElement | null>(null); const [products, setProducts] = useState<Product[]>([]); const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState<Draft>(emptyDraft); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const request = useCallback(async (init?: RequestInit) => { const { data } = await getSupabaseBrowser().auth.getSession(); if (!data.session) throw new Error("Admin session expired"); const response = await fetch("/api/admin/store/products", { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${data.session.access_token}`, ...(init?.headers ?? {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Product request failed"); return body; }, []);
  const load = useCallback(async () => { try { const body = await request(); setProducts(Array.isArray(body.products) ? body.products : []); } catch (error) { setMessage(error instanceof Error ? error.message : "Products could not be loaded"); } }, [request]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  function edit(product: Product) { setEditing(product.product_key); setDraft({ productKey: product.product_key, productName: product.product_name, description: product.description, price: (product.unit_amount_cents / 100).toFixed(2), variants: product.variants.join(", "), category: product.category, imageUrl: product.image_url ?? "", fulfillmentMode: product.fulfillment_mode, availableQuantity: String(product.available_quantity ?? 0), shippingBase: (product.shipping_base_cents / 100).toFixed(2), shippingAdditional: (product.shipping_additional_cents / 100).toFixed(2), active: product.active }); window.setTimeout(() => editorRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); }
  async function save() { setBusy(true); setMessage(""); try { const payload = { productKey: draft.productKey.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), productName: draft.productName, description: draft.description, unitAmountCents: Math.round(Number(draft.price) * 100), variants: draft.variants.split(",").map((item) => item.trim()).filter(Boolean), category: draft.category, imageUrl: draft.imageUrl, fulfillmentMode: draft.fulfillmentMode, availableQuantity: Math.trunc(Number(draft.availableQuantity)), shippingBaseCents: Math.round(Number(draft.shippingBase) * 100), shippingAdditionalCents: Math.round(Number(draft.shippingAdditional) * 100), active: draft.active }; await request({ method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); setMessage(editing ? "Product updated." : "Product added."); setEditing(null); setDraft(emptyDraft); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Product could not be saved"); } finally { setBusy(false); } }
  return <main className="section"><div className="container-app"><p className="eyebrow mb-2">Store</p><h1 className="heading-lg">Products</h1><p className="body-muted mt-2">Product changes become the source of truth for availability and Stripe checkout.</p>{message && <p role="status" className="mt-4 rounded-lg border border-slate-300 bg-white p-3 text-sm">{message}</p>}
    <section ref={editorRef} className="card mt-6 scroll-mt-24 p-5 text-white"><h2 className="text-xl font-extrabold text-white">{editing ? `Edit ${draft.productName}` : "Add product"}</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Product key" value={draft.productKey} disabled={!!editing} onChange={(value) => setDraft({ ...draft, productKey: value })} /><Field label="Name" value={draft.productName} onChange={(value) => setDraft({ ...draft, productName: value })} /><Field label="Price ($)" value={draft.price} type="number" onChange={(value) => setDraft({ ...draft, price: value })} /><Field label="Category" value={draft.category} onChange={(value) => setDraft({ ...draft, category: value })} /><label className="text-sm text-white md:col-span-2">Description<textarea className="mt-1 min-h-24 w-full rounded border bg-white p-2 text-slate-900 placeholder:text-slate-400" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><Field label="Variants (comma separated)" value={draft.variants} onChange={(value) => setDraft({ ...draft, variants: value })} /><Field label="Image URL (optional)" value={draft.imageUrl} onChange={(value) => setDraft({ ...draft, imageUrl: value })} /><label className="text-sm text-white">Fulfillment<select className="mt-1 w-full rounded border bg-white p-2 text-slate-900" value={draft.fulfillmentMode} onChange={(event) => setDraft({ ...draft, fulfillmentMode: event.target.value })}><option value="made_to_order">Made to order</option><option value="stocked">Stocked</option></select></label><Field label="Available quantity" value={draft.availableQuantity} type="number" step="1" disabled={draft.fulfillmentMode !== "stocked"} onChange={(value) => setDraft({ ...draft, availableQuantity: value })} /><Field label="Base shipping ($)" value={draft.shippingBase} type="number" onChange={(value) => setDraft({ ...draft, shippingBase: value })} /><Field label="Each additional ($)" value={draft.shippingAdditional} type="number" onChange={(value) => setDraft({ ...draft, shippingAdditional: value })} /></div><label className="mt-4 flex items-center gap-2 text-sm text-white"><input type="checkbox" checked={draft.active} onChange={(event) => setDraft({ ...draft, active: event.target.checked })} /> Active and available for sale</label><div className="mt-4 flex gap-2"><button disabled={busy || !draft.productName.trim() || !draft.productKey.trim()} onClick={() => void save()} className="rounded bg-[#f26a1b] px-4 py-2 font-bold text-white disabled:opacity-50">{busy ? "Saving…" : "Save product"}</button>{editing && <button onClick={() => { setEditing(null); setDraft(emptyDraft); }} className="rounded border px-4 py-2">Cancel</button>}</div></section>
    <section className="mt-8"><h2 className="text-2xl font-extrabold text-[#172033]">Catalog</h2><div className="mt-4 grid gap-3">{products.map((product) => <article key={product.product_key} className="card grid gap-4 p-5 sm:grid-cols-[112px_1fr_auto] sm:items-start"><ProductThumbnail product={product} /><div><p className="text-xs font-bold uppercase tracking-wider text-[#f26a1b]">{product.category} · {product.active ? "active" : "hidden"}</p><h3 className="mt-1 text-lg font-extrabold">{product.product_name}</h3><p className="mt-1 max-w-2xl text-sm text-slate-600">{product.description || "No description"}</p><p className="mt-2 text-sm">{product.variants.length ? `Variants: ${product.variants.join(", ")} · ` : ""}{product.fulfillment_mode.replaceAll("_", " ")}{product.fulfillment_mode === "stocked" ? ` · ${product.available_quantity ?? 0} available` : ""}</p></div><div className="text-left sm:text-right"><strong className="text-xl">${(product.unit_amount_cents / 100).toFixed(2)}</strong><div><button onClick={() => edit(product)} className="mt-3 rounded border px-3 py-2 font-semibold">Edit</button></div></div></article>)}</div></section>
  </div></main>;
}

function Field({ label, value, onChange, type = "text", disabled = false, step }: { label: string; value: string; onChange: (value: string) => void; type?: string; disabled?: boolean; step?: string }) { return <label className="text-sm text-white">{label}<input className="mt-1 w-full rounded border bg-white p-2 text-slate-900 placeholder:text-slate-400 disabled:bg-slate-100 disabled:text-slate-500" type={type} step={step ?? (type === "number" ? "0.01" : undefined)} min={type === "number" ? "0" : undefined} inputMode={step === "1" ? "numeric" : undefined} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} /></label>; }

function ProductThumbnail({ product }: { product: Product }) { const match = product.product_key.match(/^barrier-(1|3|4|6|12|24)$/); if (match) return <div className="overflow-hidden rounded-xl border bg-white p-2"><BarrierProductVisual count={Number(match[1]) as 1 | 3 | 4 | 6 | 12 | 24} className="aspect-square w-full" label={`${match[1]} Drone Operation barrier posts`} /></div>; if (product.image_url) return <div className="overflow-hidden rounded-xl border bg-white"><img src={product.image_url} alt={product.product_name} className="aspect-square h-full w-full object-contain p-2" /></div>; return <div className="flex aspect-square items-center justify-center rounded-xl border bg-slate-50 p-2 text-center text-xs font-semibold text-slate-400">No image</div>; }
