import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { resolveContractor } from "@/lib/pilotAuth";
import { createDominicPdf } from "@/lib/dominicPdf";

export const runtime = "nodejs";

function titleCase(value: string) {
  return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await resolveContractor(req);
  if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const { id } = await params;
  const admin = getSupabaseAdmin();
  const { data: project } = await admin.from("mapping_projects")
    .select("id,name,location_snapshot,latitude,longitude,image_count,processing_completed_at,job_id,job:jobs(title,location)")
    .eq("id", id).eq("contractor_id", auth.contractor.id).maybeSingle();
  if (!project) return NextResponse.json({ error: "Project not found." }, { status: 404 });

  const [{ data: measurements }, { data: markups }, { data: deliverables }] = await Promise.all([
    admin.from("mapping_measurements").select("measurement_type,label,value,unit").eq("project_id", id).order("created_at"),
    admin.from("mapping_events").select("event_type,summary,details").eq("project_id", id).eq("event_type", "markup").order("created_at"),
    admin.from("deliverables").select("name,type,qc_passed,client_status,revision_number,client_feedback").eq("job_id", project.job_id).or("client_status.is.null,client_status.neq.superseded").order("created_at"),
  ]);

  const jobRows = project.job as unknown as Array<{ title?: string | null; location?: string | null }> | { title?: string | null; location?: string | null } | null;
  const job = Array.isArray(jobRows) ? jobRows[0] : jobRows;
  const generated = new Date().toISOString();
  const lines = [
    { text: "DOMINIC", size: 25, bold: true, gap: 3 },
    { text: "INTELLIGENT MAPPING BY DOM", size: 10, bold: true },
    { text: "Drone Operation Management | Uniquely Sophisticated | DroneOpsMan.com", size: 9, gap: 14 },
    { text: project.name, size: 19, bold: true },
    { text: `Mission: ${job?.title ?? "DOM Mission"}`, bold: true },
    { text: `Location: ${project.location_snapshot ?? job?.location ?? "Not supplied"}` },
    { text: `Project ID: ${project.id}` },
    { text: `Generated: ${generated}`, gap: 14 },
    { text: "PROJECT SUMMARY", size: 13, bold: true },
    { text: `Source images: ${project.image_count ?? 0}` },
    { text: `Coordinates: ${project.latitude != null && project.longitude != null ? `${project.latitude.toFixed(6)}, ${project.longitude.toFixed(6)}` : "Not supplied"}` },
    { text: `Processing completed: ${project.processing_completed_at ?? "Pending"}`, gap: 12 },
    { text: `MEASUREMENTS (${measurements?.length ?? 0})`, size: 13, bold: true },
    ...((measurements ?? []).map((item) => ({ text: `• ${item.label ?? titleCase(item.measurement_type)}: ${item.value} ${item.unit}` }))),
    { text: `FINDINGS / MARKUPS (${markups?.length ?? 0})`, size: 13, bold: true, gap: 6 },
    ...((markups ?? []).map((item) => ({ text: `• ${item.summary ?? titleCase(item.event_type)}` }))),
    { text: `DELIVERABLES (${deliverables?.length ?? 0})`, size: 13, bold: true, gap: 6 },
    ...((deliverables ?? []).map((item) => ({
      text: `• ${item.name}${Number(item.revision_number ?? 1) > 1 ? ` (Rev ${item.revision_number})` : ""} | ${titleCase(item.type ?? "output")} | QC: ${item.qc_passed ? "Passed" : "Pending"} | Client: ${item.client_status ? titleCase(item.client_status) : "Awaiting Review"}`,
    }))),
    { text: "DOMINIC REPORT NOTICE", size: 11, bold: true, gap: 5 },
    { text: "Generated by DOMINIC — Intelligent Mapping by DOM. Measurements and mapping outputs reflect project data available at generation time. Survey-grade use depends on capture method, control, coordinate reference system, validation, and applicable professional requirements.", size: 8 },
  ];

  const pdf = createDominicPdf(lines);
  const filename = `DOMINIC_${project.name.replace(/[^a-zA-Z0-9]+/g, "-")}_Project-Report.pdf`;
  return new NextResponse(new Uint8Array(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
