import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { getSupabaseAnonServer } from "@/lib/supabaseAnonServer";
import { WORKFLOW_ITEMS } from "@/lib/missionWorkflow";

async function context(req:NextRequest, assignmentId:string){const h=req.headers.get("authorization");if(!h)return null;const sb=getSupabaseAnonServer(h);const {data:{user}}=await sb.auth.getUser();if(!user)return null;const admin=getSupabaseAdmin();const {data:a}=await admin.from("mission_assignments").select("id,job_id,status,job:jobs(mission_request_id,checked_in_at,started_at,completed_at)").eq("id",assignmentId).maybeSingle();const {data:c}=await admin.from("contractors").select("id").eq("user_id",user.id).maybeSingle();if(!a||!c)return null;const {data:owned}=await admin.from("mission_assignments").select("id").eq("id",assignmentId).eq("contractor_id",c.id).maybeSingle();return owned?{admin,user,a}:null;}

export async function GET(req:NextRequest,{params}:{params:Promise<{assignmentId:string}>}){const {assignmentId}=await params;const x=await context(req,assignmentId);if(!x)return NextResponse.json({error:"Not authorized"},{status:401});let {data:items}=await x.admin.from("mission_checklist_items").select("*").eq("assignment_id",assignmentId).order("sort_order");if(!items?.length){await x.admin.from("mission_checklist_items").insert(WORKFLOW_ITEMS.map(([phase,key,label],i)=>({assignment_id:assignmentId,phase,item_key:key,label,sort_order:i})));({data:items}=await x.admin.from("mission_checklist_items").select("*").eq("assignment_id",assignmentId).order("sort_order"));}const job:any=Array.isArray(x.a.job)?x.a.job[0]:x.a.job;return NextResponse.json({items:items??[],job});}

export async function POST(req:NextRequest,{params}:{params:Promise<{assignmentId:string}>}){const {assignmentId}=await params;const x=await context(req,assignmentId);if(!x)return NextResponse.json({error:"Not authorized"},{status:401});const body=await req.json();const job:any=Array.isArray(x.a.job)?x.a.job[0]:x.a.job;const now=new Date().toISOString();if(body.action==="checklist"){await x.admin.from("mission_checklist_items").update({completed:!!body.completed,completed_at:body.completed?now:null}).eq("id",body.itemId).eq("assignment_id",assignmentId);}else if(["check_in","start_flight","field_complete"].includes(body.action)){const column=body.action==="check_in"?"checked_in_at":body.action==="start_flight"?"started_at":"completed_at";await x.admin.from("jobs").update({[column]:now}).eq("id",x.a.job_id);await x.admin.from("mission_activity_events").insert({mission_request_id:job.mission_request_id,job_id:x.a.job_id,assignment_id:assignmentId,actor_user_id:x.user.id,actor_role:"pilot",visibility:"shared",event_type:body.action,summary:body.action==="check_in"?"Pilot checked in on site":body.action==="start_flight"?"Flight operations started":"Field capture completed"});}else if(body.action==="incident"){if(!body.summary)return NextResponse.json({error:"Incident summary required"},{status:400});await x.admin.from("mission_incidents").insert({assignment_id:assignmentId,severity:body.severity??"observation",occurred_at:now,summary:String(body.summary).slice(0,500),details:String(body.details??"").slice(0,5000),operations_paused:!!body.operationsPaused,reported_by:x.user.id});}else return NextResponse.json({error:"Invalid action"},{status:400});return NextResponse.json({ok:true});}
