
-- Phase 2: Airspace classification cache + quoting engine + pre-flight checklists

-- Airspace data cached per mission (avoid re-querying the API)
create table if not exists mission_airspace (
  id uuid primary key default gen_random_uuid(),
  mission_request_id uuid not null references mission_requests(id) on delete cascade,
  latitude numeric not null,
  longitude numeric not null,
  airspace_class text not null default 'UNKNOWN',
  max_altitude_ft integer default 400,
  nearest_airport_icao text,
  nearest_airport_name text,
  nearest_airport_distance_nm numeric,
  laanc_required boolean not null default false,
  laanc_status text not null default 'not_required',
  tfr_active boolean not null default false,
  risk_level text not null default 'low',
  authorization_summary text,
  raw_source text default 'faa_estimate',
  raw_response jsonb,
  queried_at timestamptz not null default now(),
  unique (mission_request_id)
);

-- Quotes generated by the quoting engine
create table if not exists quotes (
  id uuid primary key default gen_random_uuid(),
  mission_request_id uuid not null references mission_requests(id) on delete cascade,
  service_type text not null,
  base_price_cents integer not null,
  location_mod numeric not null default 1.0,
  airspace_mod numeric not null default 1.0,
  complexity_mod numeric not null default 1.0,
  urgency_mod numeric not null default 1.0,
  deliverable_mod numeric not null default 1.0,
  combined_multiplier numeric not null default 1.0,
  total_cents integer not null,
  commission_cents integer not null,
  contractor_cents integer not null,
  status text not null default 'draft',
  warnings text[],
  sent_at timestamptz,
  accepted_at timestamptz,
  rejected_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

-- Pre-flight checklist items (auto-generated from SOPs per mission)
create table if not exists checklist_items (
  id uuid primary key default gen_random_uuid(),
  mission_request_id uuid not null references mission_requests(id) on delete cascade,
  sop_document_id uuid references sop_documents(id) on delete set null,
  category text not null,
  item_text text not null,
  completed boolean not null default false,
  completed_by text,
  completed_at timestamptz,
  sort_order integer default 0,
  created_at timestamptz not null default now()
);

-- Communication log per mission
create table if not exists mission_comms (
  id uuid primary key default gen_random_uuid(),
  mission_request_id uuid not null references mission_requests(id) on delete cascade,
  direction text not null default 'outbound',
  channel text not null default 'email',
  subject text,
  body text,
  sender text,
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_airspace_mission on mission_airspace(mission_request_id);
create index if not exists idx_quotes_mission on quotes(mission_request_id);
create index if not exists idx_quotes_status on quotes(status);
create index if not exists idx_checklist_mission on checklist_items(mission_request_id);
create index if not exists idx_comms_mission on mission_comms(mission_request_id);

-- RLS
alter table mission_airspace enable row level security;
alter table quotes enable row level security;
alter table checklist_items enable row level security;
alter table mission_comms enable row level security;

-- Admin access
do $$
declare t text;
begin
  foreach t in array array['mission_airspace','quotes','checklist_items','mission_comms']
  loop
    execute format('drop policy if exists "admins full access" on %I;', t);
    execute format(
      'create policy "admins full access" on %I for all to authenticated using (is_admin()) with check (is_admin());', t
    );
  end loop;
end $$;
